// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Evaluation struct {
	ID        int32              `json:"id"`
	StudentID int32              `json:"student_id"`
	AuthorID  int32              `json:"author_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Student struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Gender      string             `json:"gender"`
	Phone       pgtype.Text        `json:"phone"`
	ParentPhone pgtype.Text        `json:"parent_phone"`
	Remarks     pgtype.Text        `json:"remarks"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int32              `json:"id"`
	Username     string             `json:"username"`
	Name         string             `json:"name"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
