// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStudents = `-- name: CountStudents :one
SELECT COUNT(*) FROM students
WHERE
    ($1::text IS NULL OR
        name ILIKE '%' || $1::text || '%' OR
        phone ILIKE '%' || $1::text || '%' OR
        parent_phone ILIKE '%' || $1::text || '%' OR
        remarks ILIKE '%' || $1::text || '%')
    AND ($2::text IS NULL OR gender = $2::text)
`

type CountStudentsParams struct {
	Search pgtype.Text `json:"search"`
	Gender pgtype.Text `json:"gender"`
}

func (q *Queries) CountStudents(ctx context.Context, arg CountStudentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudents, arg.Search, arg.Gender)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (name, gender, phone, parent_phone, remarks)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, gender, phone, parent_phone, remarks, created_at, updated_at
`

type CreateStudentParams struct {
	Name        string      `json:"name"`
	Gender      string      `json:"gender"`
	Phone       pgtype.Text `json:"phone"`
	ParentPhone pgtype.Text `json:"parent_phone"`
	Remarks     pgtype.Text `json:"remarks"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.Name,
		arg.Gender,
		arg.Phone,
		arg.ParentPhone,
		arg.Remarks,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.Phone,
		&i.ParentPhone,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStudent = `-- name: DeleteStudent :exec
DELETE FROM students
WHERE id = $1
`

func (q *Queries) DeleteStudent(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteStudent, id)
	return err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, name, gender, phone, parent_phone, remarks, created_at, updated_at
FROM students
WHERE id = $1
`

func (q *Queries) GetStudentByID(ctx context.Context, id int32) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.Phone,
		&i.ParentPhone,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many
SELECT id, name, gender, phone, parent_phone, remarks, created_at, updated_at
FROM students
WHERE
    ($3::text IS NULL OR
        name ILIKE '%' || $3::text || '%' OR
        phone ILIKE '%' || $3::text || '%' OR
        parent_phone ILIKE '%' || $3::text || '%' OR
        remarks ILIKE '%' || $3::text || '%')
    AND ($4::text IS NULL OR gender = $4::text)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListStudentsParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Search pgtype.Text `json:"search"`
	Gender pgtype.Text `json:"gender"`
}

func (q *Queries) ListStudents(ctx context.Context, arg ListStudentsParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudents,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.Gender,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gender,
			&i.Phone,
			&i.ParentPhone,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students
SET name = $2, gender = $3, phone = $4, parent_phone = $5, remarks = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, name, gender, phone, parent_phone, remarks, created_at, updated_at
`

type UpdateStudentParams struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Gender      string      `json:"gender"`
	Phone       pgtype.Text `json:"phone"`
	ParentPhone pgtype.Text `json:"parent_phone"`
	Remarks     pgtype.Text `json:"remarks"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudent,
		arg.ID,
		arg.Name,
		arg.Gender,
		arg.Phone,
		arg.ParentPhone,
		arg.Remarks,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.Phone,
		&i.ParentPhone,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
